language: node_js
node_js:
 - node
cache:
 directories:
   - node_modules
deploy:
 provider: s3
 access_key_id: "YOUR_ACCESS_KEY"
 secret_access_key: "YOUR_SECRET_KEY"
 bucket: "YOUR_S3_BUCKET"
 acl: public_read
 skip_cleanup: true
 local_dir: build_webpack
branches:
 only:
   - master
addons:
   apt:
     update: true
