language: node_js
node_js:
 - node
cache:
 directories:
   - node_modules
deploy:
 provider: s3
 access_key_id: "AKIAYFMNIQVZLCQV7TF5"
 secret_access_key: "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"
 bucket: "my-demo-app"
 acl: public_read
 skip_cleanup: true
 local_dir: dist
branches:
 only:
   - master
addons:
   apt:
     update: true
